### ISSUE TITLE
[💡 FEAT] 업적 도메인 구현

### ISSUE THREAD

**Issue by happyjamy** [Open-Eye-Im-Developer/MoGakGo-BE#182]
## ✨ 구현 할 기능
업적 도메인 구현

## 📢 구현 방식
업적 도메인 구현

## 📑 기능 명세
- [ ] 업적 도메인 구현

<br>

### 📕 래퍼런스

![출석체크 아이콘](https://github.com/Open-Eye-Im-Developer/MoGakGo-BE/assets/78072370/99e8a4e3-15c9-444d-b2a1-67795ce49582)

![매칭 횟수에 따른 업적 아이콘](https://github.com/Open-Eye-Im-Developer/MoGakGo-BE/assets/78072370/ff6bfae7-74c3-4572-9499-ecd5c2df078d)

![연속 매칭 업적 아이콘](https://github.com/Open-Eye-Im-Developer/MoGakGo-BE/assets/78072370/f2eb0b21-a7f3-49e8-b9e2-5b2a8a60fc52)

![너는 내운명 업적 아이콘](https://github.com/Open-Eye-Im-Developer/MoGakGo-BE/assets/78072370/3f0b987d-2ac6-49e8-94a4-45ef9baa2744)

![여러요청 업적 아이콘](https://github.com/Open-Eye-Im-Developer/MoGakGo-BE/assets/78072370/9aa5f2e9-ee34-415d-8797-352ba6b37afc)

![연속 프로젝트 생성 업적 아이콘](https://github.com/Open-Eye-Im-Developer/MoGakGo-BE/assets/78072370/4b8aa1ed-d2ea-4412-8abb-ddc534da06ef)

![탐험가 업적 아이콘](https://github.com/Open-Eye-Im-Developer/MoGakGo-BE/assets/78072370/dce19e5b-fc3f-4a11-b914-58ea61914bac)

![나만의 흔적 남기기 업적 아이콘](https://github.com/Open-Eye-Im-Developer/MoGakGo-BE/assets/78072370/615c995b-b2e8-47f2-b5af-be4703114ecf)

**Comment by tidavid1** [comment]
![image](https://github.com/Open-Eye-Im-Developer/MoGakGo-BE/assets/85854384/64d8915f-94b6-43c6-aa50-034198beb921)

![image](https://github.com/Open-Eye-Im-Developer/MoGakGo-BE/assets/85854384/06db6ca7-259d-4ad0-882e-43be4f4cb3da)

![image](https://github.com/Open-Eye-Im-Developer/MoGakGo-BE/assets/85854384/bd3da740-754c-44a4-9c3c-569e16180fc3)

![candidate_11937743](https://github.com/Open-Eye-Im-Developer/MoGakGo-BE/assets/85854384/78d3b1d0-0b9e-47d5-b25c-eab6ef9fa762)

![saint-joseph_12934420](https://github.com/Open-Eye-Im-Developer/MoGakGo-BE/assets/85854384/18cccbcc-259e-4244-a7c4-4c2e467f9d7b)

![vlogger_2958817](https://github.com/Open-Eye-Im-Developer/MoGakGo-BE/assets/85854384/b34764f5-bfc2-4a02-a0d2-900e4cc719a9)
